'use client'

import { useEffect, useState } from 'react'
import type { AttendanceStatusData, AttendanceStatusParty, AttendanceStatusPlayer, AttendancePreviousEvent } from '@/lib/attendance-status'

function formatTime(value: string | null) { return value ? new Intl.DateTimeFormat('es-ES', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '—' }
function remaining(expiresAt: string | null, now: number) { if (!expiresAt) return '—'; const seconds = Math.max(0, Math.floor((new Date(expiresAt).getTime() - now) / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }

export function AttendanceStatus({ initialData }: { initialData: AttendanceStatusData }) {
  const [data, setData] = useState(initialData)
  const [now, setNow] = useState(() => Date.now())
  useEffect(() => { let active = true; const refresh = async () => { try { const response = await fetch('/api/attendance/status', { cache: 'no-store' }); if (response.ok && active) setData(await response.json() as AttendanceStatusData) } catch { /* Keep the last known state during a transient polling failure. */ } }; const poll = window.setInterval(refresh, 7000); const clock = window.setInterval(() => setNow(Date.now()), 1000); return () => { active = false; window.clearInterval(poll); window.clearInterval(clock) } }, [])
  if (!data.event) return <div className="space-y-8"><section className="rounded-3xl border border-white/10 bg-card/80 p-10 text-center"><h2 className="text-xl font-semibold">No hay una asistencia activa.</h2><p className="mt-2 text-sm text-muted-foreground">Cuando el staff abra una asistencia, aquí podrás ver el estado del Board.</p></section><PreviousAttendances events={data.previousEvents} /></div>
  const ended = Boolean(data.event.expiresAt && new Date(data.event.expiresAt).getTime() <= now)
  return <div className="space-y-8">
    <section className="rounded-3xl border border-emerald-400/20 bg-card/80 p-6 shadow-2xl shadow-black/20 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-violet-300/80">Attendance en vivo</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Asistencia · {data.event.name}</h2><p className="mt-3 text-sm text-muted-foreground">Board: <strong className="text-foreground">{data.event.board?.name ?? 'Sin board seleccionado'}</strong></p><p className={`mt-3 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm font-medium ${ended ? 'border-white/10 bg-white/5 text-muted-foreground' : 'border-emerald-400/20 bg-emerald-400/10 text-emerald-200'}`}><span aria-hidden="true">●</span> {ended ? 'FINALIZADA' : 'ACTIVA'}</p></div><div className="rounded-2xl border border-amber-400/20 bg-amber-400/10 px-5 py-4 text-center"><p className="text-xs uppercase tracking-[0.16em] text-amber-200/80">{ended ? 'Finalizó' : 'Expira en'}</p><p className="mt-1 font-mono text-2xl font-semibold text-amber-100">{ended ? formatTime(data.event.expiresAt) : remaining(data.event.expiresAt, now)}</p></div></div><div className="mt-8 grid gap-3 sm:grid-cols-4"><Stat value={`${data.expectedPresent} / ${data.totalExpected}`} label="Esperados presentes" /><Stat value={`${data.percentage}%`} label="Asistencia esperada" /><Stat value={String(data.totalRegistered)} label="Presentes totales" /><Stat value={formatTime(data.event.openedAt)} label="Apertura" /></div>{data.replacements.length > 0 && <p className="mt-4 text-sm text-emerald-300">+ {data.replacements.length} reemplazo{data.replacements.length === 1 ? '' : 's'} sin party</p>}</section>
    <div className="min-w-0 space-y-5"><h3 className="text-sm font-semibold uppercase tracking-[0.2em] text-violet-300">Parties del Board</h3><div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{data.parties.map((party) => <PartyCard key={party.id} party={party} />)}</div>{data.replacements.length > 0 && <section className="min-w-0 rounded-2xl border border-emerald-400/20 bg-emerald-400/5" aria-labelledby="replacements-heading"><div className="border-b border-emerald-400/10 px-4 py-3"><h3 id="replacements-heading" className="truncate font-semibold text-emerald-200">SIN PARTY / REEMPLAZOS <span className="text-muted-foreground">({data.replacements.length})</span></h3></div><div className="grid min-w-0 gap-2 p-4 sm:grid-cols-2">{data.replacements.map((player) => <PlayerRow key={player.id} player={player} />)}</div></section>}</div>
  <PreviousAttendances events={data.previousEvents} /></div>
}
function PreviousAttendances({ events }: { events: AttendancePreviousEvent[] }) { const format = (value: string) => new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); return <section className="space-y-3" aria-labelledby="previous-attendances"><h2 id="previous-attendances" className="text-sm font-semibold uppercase tracking-[0.2em] text-violet-300">Asistencias anteriores</h2>{events.length ? events.map((event) => <a key={event.id} href={`/attendance/history?event=${encodeURIComponent(event.id)}`} className="flex min-w-0 flex-col gap-3 rounded-2xl border border-white/10 bg-card/70 p-4 transition hover:border-violet-400/40 hover:bg-violet-400/5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h3 className="truncate font-medium" title={event.name}>{event.name}</h3><p className="mt-1 text-sm text-muted-foreground">{format(event.occurredAt)}</p><p className="mt-1 text-sm text-muted-foreground">Asistentes: <span className="font-medium text-foreground">{event.present}/{event.expected}</span></p></div><span className="shrink-0 text-sm font-medium text-violet-200">Ver más detalles →</span></a>) : <p className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-muted-foreground">Todavía no hay asistencias anteriores.</p>}</section> }
function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-2xl bg-white/[0.04] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div> }
function PartyCard({ party }: { party: AttendanceStatusParty }) { const present = party.players.filter((player) => player.present).length; return <section className="min-w-0 overflow-hidden rounded-2xl border border-white/10 bg-card/80 p-4" aria-labelledby={`party-${party.id}`}><div className="flex min-w-0 items-center justify-between gap-2"><h3 id={`party-${party.id}`} className="min-w-0 truncate font-semibold">{party.name}</h3><span className="shrink-0 text-xs text-muted-foreground">{present}/{party.players.length}</span></div><div className="mt-3 min-w-0 space-y-2">{party.players.length ? party.players.map((player) => <PlayerRow key={player.id} player={player} />) : <p className="rounded-lg border border-dashed border-white/10 px-3 py-5 text-center text-xs text-muted-foreground">Sin jugadores asignados.</p>}</div></section> }
function PlayerRow({ player }: { player: AttendanceStatusPlayer }) { return <div className={`min-w-0 overflow-hidden rounded-xl border px-3 py-2 ${player.present ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-100' : 'border-white/10 bg-background/40 text-muted-foreground'}`}><div className="flex min-w-0 items-center gap-2"><span className={`size-2 shrink-0 rounded-full ${player.present ? 'bg-emerald-300 shadow-[0_0_10px_rgba(110,231,183,0.8)]' : 'bg-zinc-600'}`} aria-hidden="true" /><span className="min-w-0 flex-1 truncate text-ellipsis text-sm font-medium" title={player.name}>{player.name}</span></div><p className="mt-1 truncate pl-4 text-[10px] uppercase tracking-wide">{player.present ? `PRESENTE · ${formatTime(player.registeredAt)}` : 'AUSENTE'}</p></div> }
