'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createAttendance, closeAttendance, deleteAttendance, openAttendance } from '@/app/attendance/actions'
import { generateAttendanceCode } from '@/lib/attendance-shared'

type BoardOption = { id: string; title: string }
type EventRow = { id: string; name: string; description: string | null; duration_minutes: number; code: string; status: 'active' | 'closed'; created_at: string; opened_at: string | null; closed_at: string | null; expires_at: string | null; registered_count: number }
type RecordRow = { id: string; roster_member_id: string; created_at: string; roster_member: { display_name: string | null } | null; guild_user: { username: string } | null }

function date(value: string | null) { return value ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—' }

type ParticipantRow = { id: string; display_name: string | null; discord_user_id: string }

export function AttendanceManager({ boards, events, selected, records, participants }: { boards: BoardOption[]; events: EventRow[]; selected: EventRow | null; records: RecordRow[]; participants: ParticipantRow[] }) {
  const router = useRouter()
  const [message, setMessage] = useState('')

  useEffect(() => {
    if (!selected?.id || selected.status !== 'active') return
    const interval = window.setInterval(() => router.refresh(), 5000)
    return () => window.clearInterval(interval)
  }, [router, selected?.id, selected?.status])
  const [busy, setBusy] = useState(false)
  async function run(action: (formData: FormData) => Promise<unknown>, formData: FormData) {
    setBusy(true)
    setMessage('')
    try {
      const result = await action(formData)
      if (typeof result === 'object' && result !== null && 'ok' in result && result.ok === false && 'message' in result && typeof result.message === 'string') {
        setMessage(result.message)
        return
      }
      setMessage('Cambios guardados.')
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : typeof error === 'object' && error !== null && 'message' in error && typeof error.message === 'string' ? error.message : 'No se pudo completar la acción.'
      setMessage(message)
    } finally {
      setBusy(false)
    }
  }
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)]">
    <section className="rounded-2xl border border-white/10 bg-black/10 p-5" aria-labelledby="create-attendance"><h2 id="create-attendance" className="font-semibold">Crear asistencia</h2><form className="mt-5 space-y-4" onSubmit={(event) => { event.preventDefault(); void run(createAttendance, new FormData(event.currentTarget)) }}><input name="name" required maxLength={120} placeholder="Nombre del evento" className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm outline-none focus:border-violet-400" /><textarea name="description" maxLength={1000} placeholder="Descripción opcional" className="min-h-24 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm outline-none focus:border-violet-400" /><label className="block text-sm"><span className="mb-2 block text-muted-foreground">Board</span><select name="board_id" required defaultValue="" className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 outline-none focus:border-violet-400"><option value="" disabled>Selecciona un Board</option>{boards.map((board) => <option key={board.id} value={board.id}>{board.title}</option>)}</select></label><label className="block text-sm"><span className="mb-2 block text-muted-foreground">Duración (minutos)</span><input name="duration_minutes" type="number" min={1} max={1440} defaultValue={15} required className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 outline-none focus:border-violet-400" /></label><div className="flex gap-2"><input name="code" type="text" required pattern="[0-9]{4}" maxLength={4} minLength={4} inputMode="numeric" autoComplete="off" placeholder="4827" aria-label="Código de asistencia de 4 dígitos" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2 font-mono text-sm outline-none focus:border-violet-400" /><button type="button" onClick={(event) => { const input = event.currentTarget.form?.elements.namedItem('code'); if (input instanceof HTMLInputElement) input.value = generateAttendanceCode() }} className="rounded-xl border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Generar</button></div><p className="text-xs text-muted-foreground">Usa exactamente 4 dígitos.</p><button disabled={busy} className="w-full rounded-xl bg-violet-400 px-4 py-2 text-sm font-medium text-black disabled:opacity-50">Crear asistencia</button>{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}</form></section>
    <section className="space-y-4" aria-labelledby="attendance-events"><div className="flex items-center justify-between"><h2 id="attendance-events" className="font-semibold">Eventos</h2><span className="text-xs text-muted-foreground">{events.length} total</span></div>{events.length === 0 ? <p className="rounded-2xl border border-dashed border-white/10 p-6 text-sm text-muted-foreground">Todavía no hay asistencias.</p> : events.map((event) => <article key={event.id} className={`rounded-2xl border p-5 ${selected?.id === event.id ? 'border-violet-400/50 bg-violet-400/5' : 'border-white/10 bg-black/10'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{event.name}</h3><p className="mt-1 text-xs text-violet-200">Duración: {event.duration_minutes} minutos</p><p className="mt-1 font-mono text-sm text-violet-200">{event.code}</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${event.status === 'active' ? 'bg-emerald-400/15 text-emerald-200' : 'bg-white/10 text-muted-foreground'}`}>{event.status === 'active' ? 'ACTIVO' : 'CERRADO'}</span></div><p className="mt-3 text-sm text-muted-foreground">{event.registered_count} registrados · creado {date(event.created_at)}{event.status === 'active' && event.expires_at ? ` · expira ${date(event.expires_at)}` : ''}</p><div className="mt-4 flex flex-wrap gap-2"><a href={`/attendance?id=${event.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-xs hover:bg-white/5">Gestionar</a>{event.status === 'active' ? <button disabled={busy} onClick={() => { const form = new FormData(); form.set('id', event.id); void run(closeAttendance, form) }} className="rounded-lg border border-amber-400/20 px-3 py-2 text-xs text-amber-200">Cerrar</button> : <button disabled={busy} onClick={() => { const form = new FormData(); form.set('id', event.id); void run(openAttendance, form) }} className="rounded-lg border border-emerald-400/20 px-3 py-2 text-xs text-emerald-200">Abrir y publicar</button>}<button disabled={busy} onClick={() => { const form = new FormData(); form.set('id', event.id); void run(deleteAttendance, form) }} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-200">Eliminar</button></div></article>)}</section>
    {selected && <section className="lg:col-span-2 rounded-2xl border border-white/10 bg-black/10 p-5" aria-labelledby="attendance-records"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="attendance-records" className="font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-muted-foreground">Creado {date(selected.created_at)} · abierto {date(selected.opened_at)} · cerrado {date(selected.closed_at)}</p></div><div className="flex gap-2">{selected.status === 'active' ? <button disabled={busy} onClick={() => { const form = new FormData(); form.set('id', selected.id); void run(closeAttendance, form) }} className="rounded-lg border border-amber-400/20 px-3 py-2 text-xs text-amber-200">Cerrar asistencia</button> : <button disabled={busy} onClick={() => { const form = new FormData(); form.set('id', selected.id); void run(openAttendance, form) }} className="rounded-lg border border-emerald-400/20 px-3 py-2 text-xs text-emerald-200">Abrir asistencia</button>}</div></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="text-xs font-semibold uppercase tracking-wider text-emerald-300">Presentes ({records.length})</h3><div className="mt-2 divide-y divide-white/10">{records.length ? records.map((record) => <div key={record.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><p>{record.roster_member?.display_name ?? 'Roster member'}</p><p className="text-xs text-muted-foreground">{record.guild_user?.username ?? 'Discord user unavailable'}</p></div><time className="text-xs text-muted-foreground">{date(record.created_at)}</time></div>) : <p className="py-4 text-sm text-muted-foreground">Todavía no hay registros.</p>}</div></div><div><h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Ausentes ({Math.max(0, participants.length - participants.filter((participant) => records.some((record) => record.roster_member_id === participant.id)).length)})</h3><div className="mt-2 divide-y divide-white/10">{participants.filter((participant) => !records.some((record) => record.roster_member_id === participant.id)).map((participant) => <div key={participant.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><p>{participant.display_name ?? 'Roster member'}</p><p className="text-xs text-muted-foreground">{participant.discord_user_id}</p></div><span className="text-xs text-muted-foreground">AUSENTE</span></div>)}{participants.length === 0 && <p className="py-4 text-sm text-muted-foreground">Este evento no tiene snapshot de roster.</p>}</div></div></div></section>}
  </div>
}
