'use client'

import { DndContext, DragEndEvent, DragOverlay, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from '@dnd-kit/core'
import { CSS } from '@dnd-kit/utilities'
import { useRouter } from 'next/navigation'
import { useState, type FormEvent, type ReactNode } from 'react'
import { assignRosterMember, createBoard, createParty, deleteBoard, deleteParty, moveRosterMember, removeRosterMemberFromBoard, updateBoard } from '@/app/board/actions'
import type { Board, BoardAssignment, BoardParty } from '@/lib/board'
import type { RosterMember } from '@/lib/auth/users'

type Props = { boards: Board[]; activeBoard: Board | null; parties: BoardParty[]; assignments: BoardAssignment[]; roster: RosterMember[]; canManage: boolean }
const roleStyles = { DPS: 'border-red-400/30 bg-red-400/10', HEAL: 'border-emerald-400/30 bg-emerald-400/10', TANK: 'border-blue-400/30 bg-blue-400/10' } as const

function DraggablePlayer({ member, assignment, canManage, children }: { member: RosterMember; assignment?: BoardAssignment; canManage: boolean; children?: ReactNode }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: member.id, disabled: !canManage, data: { assignmentId: assignment?.id, memberId: member.id } })
  return <div ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} className={`${isDragging ? 'opacity-30' : ''} ${canManage ? 'cursor-grab active:cursor-grabbing' : ''}`} {...listeners} {...attributes}>{children}</div>
}

function PlayerCard({ member, assignment, canManage, onRemove }: { member: RosterMember; assignment?: BoardAssignment; canManage: boolean; onRemove?: () => void }) {
  return <DraggablePlayer member={member} assignment={assignment} canManage={canManage}><div className={`rounded-xl border px-3 py-2 ${roleStyles[member.combat_role as keyof typeof roleStyles] ?? 'border-white/10 bg-background/40'}`}><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2">{member.profile_image_signed_url ? <img src={member.profile_image_signed_url} alt="" className="size-8 rounded-full object-cover" /> : <span className="flex size-8 items-center justify-center rounded-full bg-violet-400/15 text-[10px] font-bold text-violet-200">{(member.display_name || member.discord_user_id).slice(0, 2).toUpperCase()}</span>}<div><p className="font-medium">{member.display_name || member.discord_user_id}</p><p className="text-xs text-muted-foreground">{member.class_name || 'Clase sin definir'} · {member.combat_role}</p></div></div>{onRemove && <button type="button" onClick={(event) => { event.stopPropagation(); onRemove() }} className="text-xs text-muted-foreground hover:text-foreground" aria-label={`Quitar a ${member.display_name || 'jugador'}`}>Quitar</button>}</div></div></DraggablePlayer>
}

function DropZone({ id, children, className = '' }: { id: string; children: ReactNode; className?: string }) { const { isOver, setNodeRef } = useDroppable({ id }); return <div ref={setNodeRef} className={`${className} ${isOver ? 'ring-2 ring-amber-400/80' : ''}`}>{children}</div> }

export function BoardManager({ boards, activeBoard, parties, assignments, roster, canManage }: Props) {
  const router = useRouter(); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }))
  const [message, setMessage] = useState<string | null>(null); const [boardTitle, setBoardTitle] = useState(''); const [partyTitle, setPartyTitle] = useState(''); const [editingBoardId, setEditingBoardId] = useState<string | null>(null); const [editingBoardTitle, setEditingBoardTitle] = useState(''); const [activeDrag, setActiveDrag] = useState<string | null>(null)
  const assigned = new Set(assignments.map((item) => item.roster_member_id)); const activeRoster = roster.filter((member) => member.is_active); const available = activeRoster.filter((member) => !assigned.has(member.id))
  async function run(action: () => Promise<void>, success: string) { try { await action(); setMessage(success); router.refresh() } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo completar la acción.') } }
  function formData(values: Record<string, string>) { const data = new FormData(); Object.entries(values).forEach(([key, value]) => data.set(key, value)); return data }
  const submitBoard = (event: FormEvent) => { event.preventDefault(); void run(() => createBoard(formData({ title: boardTitle })), 'Board creado.'); setBoardTitle('') }
  const submitParty = (event: FormEvent) => { event.preventDefault(); if (!activeBoard) return; void run(() => createParty(formData({ boardId: activeBoard.id, title: partyTitle, sortOrder: String(parties.length) })), 'Party creada.'); setPartyTitle('') }
  async function handleDragEnd(event: DragEndEvent) { setActiveDrag(null); if (!canManage || !activeBoard || !event.over) return; const member = roster.find((item) => item.id === event.active.id); if (!member) return; const target = String(event.over.id); if (target === 'available') { const assignment = assignments.find((item) => item.roster_member_id === member.id); if (assignment) await run(() => removeRosterMemberFromBoard(formData({ id: assignment.id })), 'Jugador devuelto al roster.'); return } const party = parties.find((item) => item.id === target); if (!party) return; const partyAssignments = assignments.filter((item) => item.party_id === party.id); const source = assignments.find((item) => item.roster_member_id === member.id); if (source?.party_id === party.id) return; if (partyAssignments.length >= 6) { setMessage('Esta party ya tiene 6 jugadores.'); return } if (source) await run(() => moveRosterMember(formData({ boardId: activeBoard.id, id: source.id, partyId: party.id, sortOrder: String(partyAssignments.length) })), 'Jugador movido.'); else await run(() => assignRosterMember(formData({ boardId: activeBoard.id, partyId: party.id, rosterMemberId: member.id, sortOrder: String(partyAssignments.length) })), 'Jugador asignado.') }
  const draggedMember = activeDrag ? roster.find((item) => item.id === activeDrag) : undefined
  return <DndContext sensors={sensors} onDragStart={(event) => setActiveDrag(String(event.active.id))} onDragCancel={() => setActiveDrag(null)} onDragEnd={handleDragEnd}>
    <div className="space-y-6">
      {message && <p role="status" className="rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-3 text-sm text-violet-100">{message}</p>}
      {canManage && <section className="grid gap-4 lg:grid-cols-2"><form onSubmit={submitBoard} className="rounded-2xl border border-white/10 bg-card/80 p-5"><h2 className="font-semibold">Nuevo board</h2><div className="mt-4 flex gap-2"><input value={boardTitle} onChange={(event) => setBoardTitle(event.target.value)} maxLength={120} required placeholder="Ej. Raid semanal" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-background px-3 py-2 text-sm"/><button className="rounded-lg bg-amber-500 px-4 py-2 text-sm font-semibold text-white">Crear</button></div></form><form onSubmit={submitParty} className="rounded-2xl border border-white/10 bg-card/80 p-5"><h2 className="font-semibold">Nueva party {activeBoard && <span className="text-sm font-normal text-muted-foreground">en {activeBoard.title}</span>}</h2><div className="mt-4 flex gap-2"><input value={partyTitle} onChange={(event) => setPartyTitle(event.target.value)} maxLength={80} required disabled={!activeBoard} placeholder="Ej. Grupo principal" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-background px-3 py-2 text-sm"/><button disabled={!activeBoard} className="rounded-lg bg-amber-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Agregar Party</button></div></form></section>}
      <section className="rounded-2xl border border-white/10 bg-card/80 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300/80">Boards</p><h2 className="mt-1 text-xl font-semibold">Planificación de parties</h2></div>{activeBoard && <span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200">Actual: {activeBoard.title}</span>}</div><div className="mt-5 space-y-2">{boards.map((board) => <div key={board.id} className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => router.push(`/board?board=${board.id}`)} className={`min-w-0 max-w-full truncate rounded-lg border px-3 py-2 text-left text-sm ${board.id === activeBoard?.id ? 'border-amber-400 bg-amber-400/15 text-violet-100' : 'border-white/10 text-muted-foreground'}`}>{board.title}</button>{canManage && (editingBoardId === board.id ? <form onSubmit={(event) => { event.preventDefault(); if (!editingBoardTitle.trim()) { setMessage('El nombre del Board no puede estar vacío.'); return }; void run(() => updateBoard(formData({ id: board.id, title: editingBoardTitle })), 'Board renombrado.'); setEditingBoardId(null) }} className="flex min-w-[240px] flex-1 gap-2 sm:flex-none"><input value={editingBoardTitle} onChange={(event) => setEditingBoardTitle(event.target.value)} maxLength={120} autoFocus aria-label={`Nuevo nombre para ${board.title}`} className="min-w-0 flex-1 rounded-lg border border-amber-400/40 bg-background px-3 py-2 text-sm"/><button className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Guardar</button><button type="button" onClick={() => setEditingBoardId(null)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Cancelar</button></form> : <><button type="button" onClick={() => { setEditingBoardId(board.id); setEditingBoardTitle(board.title) }} className="rounded-lg border border-white/10 px-2 py-2 text-xs text-muted-foreground hover:text-foreground">Editar nombre</button><button type="button" onClick={() => { if (window.confirm(`¿Eliminar el Board “${board.title}”? Esta acción no elimina el roster ni las asistencias históricas.`)) void run(() => deleteBoard(formData({ id: board.id })), 'Board eliminado.') }} className="rounded-lg border border-red-400/20 px-2 py-2 text-xs text-red-300 hover:bg-red-400/10">Eliminar</button></>)}</div>)}</div></section>
      {activeBoard && <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><section className="min-w-0"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Parties <span className="text-sm font-normal text-muted-foreground">{parties.length} total · máximo 6 jugadores por party</span></h2></div><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{parties.map((party) => { const partyAssignments = assignments.filter((item) => item.party_id === party.id); return <DropZone key={party.id} id={party.id} className="rounded-2xl border border-white/10 bg-card/80 p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{party.title}</h3><span className="text-xs text-muted-foreground">{partyAssignments.length}/6</span></div><div className="mt-3 space-y-2">{partyAssignments.map((assignment) => { const member = roster.find((item) => item.id === assignment.roster_member_id); return member ? <PlayerCard key={assignment.id} member={member} assignment={assignment} canManage={canManage} onRemove={canManage ? () => void run(() => removeRosterMemberFromBoard(formData({ id: assignment.id })), 'Jugador devuelto al roster.') : undefined} /> : null })}</div>{!partyAssignments.length && <p className="mt-4 rounded-lg border border-dashed border-white/10 px-3 py-5 text-center text-xs text-muted-foreground">Suelta jugadores aquí</p>}{canManage && <button type="button" onClick={() => void run(() => deleteParty(formData({ id: party.id })), 'Party eliminada.')} className="mt-4 text-xs text-muted-foreground hover:text-red-300">Eliminar party</button>}</DropZone>})}</div></section><aside className="xl:sticky xl:top-6"><DropZone id="available" className="rounded-2xl border border-amber-400/20 bg-card/80 p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Roster Disponible</h2><span className="text-xs text-muted-foreground">{available.length}</span></div><p className="mt-1 text-xs text-muted-foreground">{canManage ? 'Arrastra un jugador a cualquier party.' : 'Solo lectura para miembros.'}</p><div className="mt-4 space-y-2">{available.map((member) => <PlayerCard key={member.id} member={member} canManage={canManage} />)}{!available.length && <p className="rounded-lg border border-dashed border-white/10 px-3 py-5 text-center text-xs text-muted-foreground">Todos están asignados.</p>}</div></DropZone></aside></div>}
    </div><DragOverlay>{draggedMember ? <div className="w-60"><PlayerCard member={draggedMember} canManage={false} /></div> : null}</DragOverlay>
  </DndContext>
}

export default BoardManager
