export const WEAPONS = [
  { value: 'greatsword', label: 'Espadón' }, { value: 'sword_shield', label: 'Espada y Escudo' },
  { value: 'daggers', label: 'Dagas' }, { value: 'spear', label: 'Lanza' }, { value: 'knuckles', label: 'Puños' },
  { value: 'longbow', label: 'Arco Largo' }, { value: 'crossbow', label: 'Ballesta' }, { value: 'staff', label: 'Báculo' },
  { value: 'wand_tome', label: 'Varita y Tomo' }, { value: 'orb', label: 'Orbe' },
] as const
export type WeaponValue = typeof WEAPONS[number]['value']
const pair = (a: WeaponValue, b: WeaponValue) => [a, b].sort().join('|')
const CLASS_BY_PAIR: Record<string, string> = {
  [pair('knuckles', 'staff')]: 'Archon', [pair('crossbow', 'staff')]: 'Battleweaver', [pair('sword_shield', 'daggers')]: 'Berserker', [pair('spear', 'crossbow')]: 'Cavalier', [pair('orb', 'crossbow')]: 'Crucifix', [pair('greatsword', 'sword_shield')]: 'Crusader', [pair('daggers', 'wand_tome')]: 'Darkblighter', [pair('knuckles', 'spear')]: 'Destroyer', [pair('sword_shield', 'staff')]: 'Disciple', [pair('orb', 'staff')]: 'Enigma', [pair('spear', 'staff')]: 'Eradicator', [pair('crossbow', 'wand_tome')]: 'Fury', [pair('spear', 'greatsword')]: 'Gladiator', [pair('orb', 'sword_shield')]: 'Guardian', [pair('spear', 'longbow')]: 'Impaler', [pair('longbow', 'daggers')]: 'Infiltrator', [pair('staff', 'wand_tome')]: 'Invocator', [pair('knuckles', 'sword_shield')]: 'Juggernaut', [pair('orb', 'greatsword')]: 'Justicar', [pair('longbow', 'staff')]: 'Liberator', [pair('orb', 'daggers')]: 'Lunarch', [pair('knuckles', 'greatsword')]: 'Mauler', [pair('knuckles', 'longbow')]: 'Mobilist', [pair('orb', 'wand_tome')]: 'Oracle', [pair('crossbow', 'greatsword')]: 'Outrider', [pair('greatsword', 'wand_tome')]: 'Paladin', [pair('orb', 'spear')]: 'Polaris', [pair('knuckles', 'daggers')]: 'Predator', [pair('crossbow', 'sword_shield')]: 'Raider', [pair('longbow', 'greatsword')]: 'Ranger', [pair('greatsword', 'daggers')]: 'Ravager', [pair('crossbow', 'daggers')]: 'Scorpion', [pair('longbow', 'crossbow')]: 'Scout', [pair('orb', 'longbow')]: 'Scryer', [pair('longbow', 'wand_tome')]: 'Seeker', [pair('staff', 'greatsword')]: 'Sentinel', [pair('spear', 'daggers')]: 'Shadowdancer', [pair('knuckles', 'crossbow')]: 'Shrike', [pair('knuckles', 'orb')]: 'Soulcrusher', [pair('staff', 'daggers')]: 'Spellblade', [pair('spear', 'sword_shield')]: 'Steelheart', [pair('sword_shield', 'wand_tome')]: 'Templar', [pair('knuckles', 'wand_tome')]: 'Tormentor', [pair('spear', 'wand_tome')]: 'Voidlance', [pair('sword_shield', 'longbow')]: 'Warden',
}
export function deriveClass(weapon1: string | null | undefined, weapon2: string | null | undefined) { if (!weapon1 || !weapon2 || weapon1 === weapon2) return 'Unassigned'; return CLASS_BY_PAIR[pair(weapon1 as WeaponValue, weapon2 as WeaponValue)] ?? 'Unassigned' }
export function weaponLabel(value: string | null | undefined) { return WEAPONS.find((weapon) => weapon.value === value)?.label ?? value ?? '—' }
export const isWeapon = (value: string): value is WeaponValue => WEAPONS.some((weapon) => weapon.value === value)
